name: Scheduled HNB Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      run: python SP_last3.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@://github.com'

    - name: Stage Data File
      run: git add data.json

    - name: Commit and Push Changes
      run: |
        # Check if there are modified files staged for commit
        if ! git diff-index --quiet HEAD --; then
          echo "Changes detected in data.json. Committing..."
          git commit -m "Automated update of HNB data"
          git push origin main
        else
          echo "No new changes detected in data.json. Skipping commit."
        fi

